### ISSUE TITLE
Incorrect documentation for set_properties_value

### ISSUE THREAD

**Issue by casconed** [Kerizer/fastlane-plugin-properties#1]
Documentation uses `name` but that results in an error:

`Could not find option 'name' in the list of available options: key, value, path`

Documentation shows:
```
  set_properties_value(
    path: "./Configs/versions.properties",
    name: "VERSION_NAME",
    value: "0.2.0"
  )
```

Should be:
```
  set_properties_value(
    path: "./Configs/versions.properties",
    key: "VERSION_NAME",
    value: "0.2.0"
  )
```

**Comment by Kerizer** [comment]
Hi, thanks for pointing this out, I've updated the documentation. If you will find any another issues feel free to create more issues :)
